config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index", as: "about"
  root to: "main#index"
  get "sign_up", to: "registerations#new"
  post "sign_up", to: "registerations#create"

  delete "logout", to: "sessions#destroy"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
#{email:string}
#{password_digest:string}
#
#{password : string virtual}
#{password_confirmation: string virtual}
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Invalid Email address"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end
    def require_user_logged_in
        redirect_to sign_in_path, alert: 'You must be logged in' if Current.user.nil?
    end
    def require_user_logged_out
        redirect_to root_path, alert: 'You must be logged out' if Current.user
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    def index
        # if session[:user_id]
        #     @user = User.find_by(id: session[:user_id])
        #     flash.now[:notice] = "Welcome to website!! " + @user.email
        # else
        #     flash.now[:notice] = "Welcome to website!!"
        # end

    end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in
    def edit

    end
    def update

    end
end

app/controllers/registerations_controller.rb
class RegisterationsController < ApplicationController
    before_action :require_user_logged_out
    def new
        @user = User.new
    end
    def create
        # => [["email", "mohammed@m.com"], 
        #["password_digest", "[FILTERED]"], 
        #"created_at", "2022-01-29 15:26:45.022237"], 
        #["updated_at", "2022-01-29 15:26:45.022237"]]
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: 'User was successfully created'
        else
            render :new
        end
    end

    
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_user_logged_out, only: [:new,:create]
    def new
        
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to root_path, notice: "Logged in successfully"
        else
          flash[:alert] = "Invalid email or password"
          render :new
        end
    end
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!!"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchedualedTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> <%=
    javascript_importmap_tags %>
  </head>

  <body>
    <div class="header">
      <%= render partial: "shared/navbar" %>
    </div>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex justify-content-center align-content-center">
  <h1>Welcome to scheduled tweets</h1>
</div>

app/views/registerations/new.erb
<h1>Create New Account</h1>
<%= form_with model: @user,local: true, url: sign_up_path, class: "row g-3" do |form| %> 
<% if @user.errors.any? %>
<div class="alert alert-danger">
  <% @user.errors.full_messages.each do |message|%>
  <div class="alert alert-info" role="alert"><%= message %></div>
  <% end %>
</div>
<% end %>
  <div class="col-md-6">
    <%= form.label :email, "Email", class: "form-label" %> 
    <%= form.text_field :email, class: "form-control",placeholder: "example@example.com"%>
  </div>
  <div class="col-md-6">
    <%= form.label :password, "Password", class: "form-label" %>
    <%=form.password_field :password, class: "form-control", placeholder:"Enter
    your password"%>
  </div>

  <div class="col-md-6">
    <%= form.label :password_confirmation, "Password Confirmation", class:
    "form-label" %> <%=form.password_field :password_confirmation, class:
    "form-control", placeholder:"Confirm your password" %>
  </div>

  <div class="col-12">
    <!-- <button type="submit" class="btn btn-primary">Create Account</button> -->
    <%= form.submit "Create Account",data: { turbo: false }, class: "btn btn-primary" %>
  </div>
<% end%>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
<div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice].inspect%>
</div>
<% end%>
<% if flash[:alert]%>
<div class="alert alert-info mt-4" role="alert">
    <%= flash[:alert].inspect%>
</div>
<% end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Navbar</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path , class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path , class: "nav-link" %>
        </li>
      </ul>
      
      <ul class="navbar-nav align-items-center ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-item">
          <%= button_to "Logout "+Current.user.email, logout_path,method:
          :delete , class: "btn btn-danger" %>
        </li>
        <li class="nav-item">
          <%= link_to "Update Password", password_path, class: "nav-link"
          %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path , class: "nav-link"
          %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", sign_in_path , class: "nav-link"
          %>
          
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>